// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfjV7ChwkfGAtvnyju1nEXh9xGhaYRYA',
    appId: '1:634586034329:web:861652017462d4fc810808',
    messagingSenderId: '634586034329',
    projectId: 'app-agrifor',
    authDomain: 'app-agrifor.firebaseapp.com',
    storageBucket: 'app-agrifor.firebasestorage.app',
    measurementId: 'G-PN93EJ9Y5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnZu7W3fCoywm_6U2CRxxZ8Dp6vRVpJY',
    appId: '1:634586034329:android:1b2a19fc2c8df789810808',
    messagingSenderId: '634586034329',
    projectId: 'app-agrifor',
    storageBucket: 'app-agrifor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZetcj_9S4w8rQ4kiJzw0Ml0jYgw3AzSM',
    appId: '1:634586034329:ios:7407a318b5f4c1dd810808',
    messagingSenderId: '634586034329',
    projectId: 'app-agrifor',
    storageBucket: 'app-agrifor.firebasestorage.app',
    androidClientId: '634586034329-1u3o17cqo3b0qre3fcqqm44cn03mmv8d.apps.googleusercontent.com',
    iosClientId: '634586034329-bngtku0nhg5m3vtv9p2o450miub4sekk.apps.googleusercontent.com',
    iosBundleId: 'br.edu.ifsc.lages.agrotechlab.agriforApp',
  );

}